import localFont from "next/font/local";
import "./globals.css";
import { DM_Sans } from '@next/font/google';

const dmSans = DM_Sans({
  subsets: ["latin"], // Choose the subsets you need
  weight: ["400", "500", "700"], // Specify the weights you need
  variable: "--font-dm-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`${dmSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
